# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# N2S: This is where the default site had icons linking to github/twitter. 
# [[social]]
# identifier = "github"
# name = "GitHub"
# url = "https://github.com/"

# [social.params]
# icon = "brand-github"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"
